services:

  postgres:
    image: postgres:18.4
    container_name: data_processing_postgre
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - data_processing_postgre:/var/lib/postgresql
    networks:
      - webproject_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4:9.16
    container_name: data_processing_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - webproject_net

  redis:
    image: redis:8-alpine
    container_name: data_processing_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - data_processing_redis:/data
    command: redis-server --appendonly yes
    networks:
      - webproject_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redisinsight:
    image: redis/redisinsight:3.6.0
    container_name: data_processing_redisinsight
    restart: always
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - webproject_net

  webproject:
    build:
      context: .
      dockerfile: WebProject/Dockerfile
    container_name: webproject_app
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__PostgreSql: "Host=postgres;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}"
      ConnectionStrings__Redis: "redis:6379"
    ports:
      - "5000:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - webproject_net

volumes:
  data_processing_postgre:
  data_processing_redis:

networks:
  webproject_net:
    driver: bridge