// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebProject.DataAccess;

#nullable disable

namespace WebProject.Migrations
{
    [DbContext(typeof(WebProjectDbContext))]
    [Migration("20260514193017_DepotData1")]
    partial class DepotData1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebProject.Models.DepotData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApproverId")
                        .HasColumnType("character varying(16)");

                    b.Property<string>("CD")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ConfirmedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DQN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DVR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DVRSt")
                        .HasColumnType("text");

                    b.Property<string>("DaySes")
                        .HasColumnType("text");

                    b.Property<int?>("Depot")
                        .HasColumnType("integer");

                    b.Property<string>("EyNom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HDDHc")
                        .HasColumnType("text");

                    b.Property<string>("HDDSM")
                        .HasColumnType("text");

                    b.Property<string>("HDDSt")
                        .HasColumnType("text");

                    b.Property<bool>("IsConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Kam")
                        .HasColumnType("text");

                    b.Property<string>("KamNom")
                        .HasColumnType("text");

                    b.Property<string>("KamSt")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("QapiR")
                        .HasColumnType("text");

                    b.Property<int>("SN")
                        .HasColumnType("integer");

                    b.Property<string>("SalMon")
                        .HasColumnType("text");

                    b.Property<string>("SayKam")
                        .HasColumnType("text");

                    b.Property<string>("SurMik")
                        .HasColumnType("text");

                    b.Property<string>("Trafared")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.ToTable("DepotData");
                });

            modelBuilder.Entity("WebProject.Models.Role", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.PrimitiveCollection<int[]>("Permissions")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Name");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("WebProject.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Username");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebProject.Models.DepotData", b =>
                {
                    b.HasOne("WebProject.Models.User", "User")
                        .WithMany("ApprovedDepotData")
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebProject.Models.User", b =>
                {
                    b.HasOne("WebProject.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebProject.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebProject.Models.User", b =>
                {
                    b.Navigation("ApprovedDepotData");
                });
#pragma warning restore 612, 618
        }
    }
}
